name: run_test
on: [pull_request]
jobs:
  build: 
    runs-on: ubuntu-latest  
    steps: 
      - uses: actions/checkout@v2
      - name: Install Modules
        run: npm install
      - name: Run Test
        run: npm test

